patchedDependencies:
  nuxt-monaco-editor: patches/nuxt-monaco-editor.patch

allowBuilds:
  '@parcel/watcher': false
  '@rolldown/browser': false
  esbuild: false

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
